### ISSUE TITLE
Alternate API less performant?

### ISSUE THREAD

**Issue by alferpal** [ckknight/random-js#15]
As per the readme file:

[Alternate API](https://github.com/ckknight/random-js#alternate-api)
>There is an alternate API which may be easier to use, but may be less performant. In scenarios where performance is paramount, it is recommended to use the aforementioned API.

Why is it less performant to create r = Random(whateverEngine) than use Random.whateverMethod(engine)? Less performant in what terms, speed, crypto security, randomness?

Excuse me if this is somewhat obvious but I can't find anything that would lead me to the answer in the documentation nor source code. 

Thank you in advance

**Comment by ckknight** [comment]
making a Random instance requires the creation of an object that manages its own state that ultimately just calls into the function-based API, leading to at least 1 extra level of indirection.

**Comment by alferpal** [comment]
Oh,  that makes sense. Thank you for the explanation.
