### ISSUE TITLE
Random.bool(percentage) not working properly

### ISSUE THREAD

**Issue by noder45** [ckknight/random-js#24]
Would it be possible to explain what's going wrong here?

C:\Users\dhd\Desktop\data>node
> var rand = require('random-js')
undefined
> var nowDate = new Date().getTime();
undefined
> var engine = rand.engines.mt19937().seed(nowDate);
undefined
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(50)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true
> rand.bool(1)(engine)
true

**Comment by kingjerod** [comment]
Did you try `rand.bool(0.5)(engine)` ? It might be expecting a float as the percentage.

**Comment by ckknight** [comment]
When providing a single percentage argument to `bool`, it is expected to be in the range of [0, 1], not [0, 100].
