### ISSUE TITLE
cannot be imported properly in jest backend 

### ISSUE THREAD

**Issue by yiakwy** [ckknight/random-js#26]
(1) When used with es6 "import" keyword, I tested a working solution
```js
import * as Random from "random-js"

let engine = Random.engines.mt19937().autoSeed()
let dist = new Random.default(engine)
```

(2) However, if I work it in jest (Facebook unit test framework for es6)

both the above codes and following codes do not work
```js
var Random = require("random-js")

let engine = Random.engines.mt19937()
let dist = new Random(engine)
```

The constructor developed here is strange for me.

**Comment by ckknight** [comment]
I believe this problem is allayed with v2.0.0-rc1. I will close this issue once v2.0.0 is officially released.

**Comment by yiakwy** [comment]
Sure. I am glad to see we have resolved the import problem for es6.
