### ISSUE TITLE
Is it possible to seed nativeMath?

### ISSUE THREAD

**Issue by JasonShin** [ckknight/random-js#28]
Hello, first of all, thanks for the great library! =)

I'm wondering, do you have any plan to support "seed" for nativeMath?

I'm currently using this library in https://github.com/JasonShin/kalimdorjs =) ..

**Comment by ckknight** [comment]
`nativeMath` is inherently unseedable. If it were, it could arguably be a security vulnerability. If you'd like a seedable PRNG, I suggest using a Mersenne Twister, which is available.
