### ISSUE TITLE
Cannot read property 'nativeMath' of undefined (2.0.0-rc2)

### ISSUE THREAD

**Issue by adanvdo** [ckknight/random-js#29]
just updated random-js in my package.  It is throwing the following.

`TypeError: Cannot read property 'nativeMath' of undefined`
 `-       at Object.<anonymous> (C:\Users\jesse\dev\wojakbot-nodejs\node_modules\rollkit\src\modules\dice.js:2:42)`
`-      at Module._compile (internal/modules/cjs/loader.js:689:30)`
`-      at Module._compile (C:\Users\jesse\dev\wojakbot-nodejs\node_modules\pirates\lib\index.js:99:24)`
`-      at Module._extensions..js (internal/modules/cjs/loader.js:700:10)`
`-      at Object.newLoader [as .js] (C:\Users\jesse\dev\wojakbot-nodejs\node_modules\pirates\lib\index.js:104:7)`
`-      at Module.load (internal/modules/cjs/loader.js:599:32)`
`-      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)`
`-      at Function.Module._load (internal/modules/cjs/loader.js:530:3)`
`-      at Module.require (internal/modules/cjs/loader.js:637:17)`
`-      at require (internal/modules/cjs/helpers.js:22:18)`

dice.js 

`const Random = require('random-js');`
`const random = new Random(Random.engines.nativeMath);`

**Comment by ckknight** [comment]
Yes, 2.0 is a major change that changed the top-level API.

What you will want to do is the following:

```js
const { Random, nativeMath } = require('random-js');
const random = new Random(nativeMath);
```

which is equivalent to

```js
const { Random } = require('random-js');
const random = new Random();
```
