### ISSUE TITLE
TypeError: n(...).Random is not a constructor

### ISSUE THREAD

**Issue by diego-betto** [ckknight/random-js#32]
Hi,

I'm trying to use with React (with TypeScript)

Import
``` JS
import { Random } from "random-js";
const random = new Random();
```

use
``` JS
...
text += possible.charAt(Math.floor((random.integer(1, 1000)/1000  ) * possible.length));
...
```

It compiles correctly but then it throws error
`TypeError: n(...).Random is not a constructor`

Any idea?

**Comment by ckknight** [comment]
That code looks correct to me. What version are you running?

**Comment by diego-betto** [comment]
2.0.0

**Comment by ckknight** [comment]
Well, if you're able to provide a reproducible test case, I'll be able to figure it out. My guess is that this is caused by your build system.

**Comment by rained23** [comment]
have same issue, using Node v10

**Comment by ckknight** [comment]
@rained23 please make a public repository that showcases the problem.

**Comment by ckknight** [comment]
Happy to work on this when I have a reproducible test case.
