### ISSUE TITLE
nativeMath returns signed integers

### ISSUE THREAD

**Issue by MikeMcl** [ckknight/random-js#6]
The README states: 

> `nativeMath`: Utilizes Math.random() and converts its result to an unsigned integer.

but looking at the code it looks like it will be a *signed* integer that is returned, as the only bitwise operator that ensures a zero sign bit is `>>>`.

```
nativeMath: function () {
  return (Math.random() * 0x100000000) | 0;
},
```      
A quick test confirms it:
```
var Random = require("random-js");
console.log( Random.engines.nativeMath() );
// -2121263325
```

**Comment by ckknight** [comment]
Ah, yes, this is an issue with the README. The code will not change, as signed integers tend to be faster (as they are often SMIs) whereas if they were unsigned, they'd have half as much chance to be an SMI.
