### ISSUE TITLE
It would be cool to optionally console.log the autoSeed'ed array.

### ISSUE THREAD

**Issue by sterpe** [ckknight/random-js#9]
Seems like a useful debug feature.  It seems straightforward.  I can put a PR together for this, but not clear how you want that API to look.

**Comment by ckknight** [comment]
Hmm, I definitely think console.log is the wrong answer, but some way to return it could be good. I just don't want performance to suffer in the typical path as a result.

**Comment by ckknight** [comment]
Closing this as `.autoSeed()` is simply just `.seedWithArray(Random.generateEntropyArray())`, which can be replicated on its own.
